import type { Item } from "./types"
import { v4 as uuidv4 } from "uuid"

export const shopItems: Item[] = [
  {
    id: uuidv4(),
    name: "Minor Healing Potion",
    type: "potion",
    value: 20,
    rarity: "common",
    health: 30,
    description: "Restores 30 health points",
  },
  {
    id: uuidv4(),
    name: "Lesser Mana Potion",
    type: "potion",
    value: 20,
    rarity: "common",
    mana: 30,
    description: "Restores 30 mana points",
  },
  {
    id: uuidv4(),
    name: "Durable Shield",
    type: "armor",
    value: 80,
    rarity: "uncommon",
    defense: 7,
    description: "A sturdy shield that provides good protection",
    classRestriction: ["warrior", "tank"],
  },
  {
    id: uuidv4(),
    name: "Magic Amulet",
    type: "accessory",
    value: 120,
    rarity: "rare",
    magic: 6,
    description: "An amulet that enhances magical abilities",
    classRestriction: ["mage"],
  },
  {
    id: uuidv4(),
    name: "Swift Boots",
    type: "armor",
    value: 90,
    rarity: "uncommon",
    stealth: 4,
    description: "Boots that allow for quieter movement",
    classRestriction: ["ranger", "thief"],
  },
  {
    id: uuidv4(),
    name: "Sharpened Dagger",
    type: "weapon",
    value: 70,
    rarity: "uncommon",
    attack: 7,
    description: "A well-crafted dagger for swift attacks",
    classRestriction: ["thief"],
  },
  {
    id: uuidv4(),
    name: "Reinforced Helm",
    type: "armor",
    value: 110,
    rarity: "rare",
    defense: 9,
    description: "A sturdy helm that protects the head",
    classRestriction: ["warrior", "tank"],
  },
  {
    id: uuidv4(),
    name: "Enchanted Bracers",
    type: "armor",
    value: 130,
    rarity: "rare",
    magic: 7,
    description: "Bracers that enhance magical power",
    classRestriction: ["mage"],
  },
  {
    id: uuidv4(),
    name: "Hunter's Bow",
    type: "weapon",
    value: 100,
    rarity: "uncommon",
    attack: 9,
    description: "A reliable bow for skilled hunters",
    classRestriction: ["ranger"],
  },
  {
    id: uuidv4(),
    name: "Shadow Cloak",
    type: "armor",
    value: 140,
    rarity: "rare",
    stealth: 8,
    description: "A cloak that helps blend into the shadows",
    classRestriction: ["thief"],
  },
]

