import type { Spell, CharacterClass } from "./types"

// Warrior Spells
export const warriorSpells: Spell[] = [
  {
    id: "warrior-1",
    name: "Mighty Slash",
    manaCost: 5,
    damage: 10,
    description: "A powerful slash that deals extra damage",
    classRestriction: ["warrior", "tank"],
    levelRequirement: 1,
  },
  {
    id: "warrior-2",
    name: "Battle Cry",
    manaCost: 10,
    effect: "Increases attack by 3 for 3 turns",
    description: "A motivating battle cry that increases your attack",
    classRestriction: ["warrior"],
    levelRequirement: 3,
  },
  {
    id: "warrior-3",
    name: "Shield Bash",
    manaCost: 8,
    damage: 5,
    effect: "Stuns enemy for 1 turn",
    description: "Bash your shield into the enemy, stunning them",
    classRestriction: ["warrior", "tank"],
    levelRequirement: 5,
  },
  {
    id: "warrior-4",
    name: "Whirlwind",
    manaCost: 15,
    damage: 12,
    effect: "Hits all enemies",
    description: "Spin around, hitting all enemies in the area",
    classRestriction: ["warrior"],
    levelRequirement: 8,
  },
  {
    id: "warrior-5",
    name: "Earthquake",
    manaCost: 30,
    damage: 20,
    effect: "Stuns all enemies for 1 turn",
    description: "Slam the ground to create a shockwave",
    classRestriction: ["warrior"],
    levelRequirement: 5,
    price: 600,
  },
  // Warrior shop spells
  {
    id: "warrior-6",
    name: "Heroic Strike",
    manaCost: 12,
    damage: 15,
    description: "A precise strike that deals significant damage",
    classRestriction: ["warrior"],
    levelRequirement: 2,
    price: 300,
  },
  {
    id: "warrior-7",
    name: "Raging Blow",
    manaCost: 18,
    damage: 22,
    description: "Channel your rage into a devastating blow",
    classRestriction: ["warrior"],
    levelRequirement: 4,
    price: 450,
  },
  {
    id: "warrior-8",
    name: "Defensive Stance",
    manaCost: 15,
    effect: "Increases defense by 5 for 3 turns",
    description: "Take a defensive stance to reduce incoming damage",
    classRestriction: ["warrior", "tank"],
    levelRequirement: 3,
    price: 350,
  },
  // New warrior spells
  {
    id: "warrior-9",
    name: "Cleave",
    manaCost: 20,
    damage: 18,
    effect: "Hits up to 3 enemies",
    description: "A wide sweeping attack that can hit multiple foes",
    classRestriction: ["warrior"],
    levelRequirement: 6,
    price: 500,
  },
  {
    id: "warrior-10",
    name: "Berserker Rage",
    manaCost: 25,
    effect: "Increases attack by 8 but reduces defense by 4 for 4 turns",
    description: "Enter a frenzied state, sacrificing defense for raw power",
    classRestriction: ["warrior"],
    levelRequirement: 7,
    price: 550,
  },
  {
    id: "warrior-11",
    name: "Evasive Maneuver",
    manaCost: 15,
    effect: "Increases dodge chance by 15% for 3 turns",
    description: "A tactical movement that makes you harder to hit",
    classRestriction: ["warrior"],
    levelRequirement: 4,
    price: 400,
  },
]

// Mage Spells
export const mageSpells: Spell[] = [
  {
    id: "mage-1",
    name: "Fireball",
    manaCost: 8,
    damage: 12,
    description: "Launches a ball of fire at the enemy",
    classRestriction: ["mage"],
    levelRequirement: 1,
  },
  {
    id: "mage-2",
    name: "Ice Spike",
    manaCost: 10,
    damage: 8,
    effect: "Slows enemy for 2 turns",
    description: "Launches a spike of ice that slows the enemy",
    classRestriction: ["mage"],
    levelRequirement: 2,
  },
  {
    id: "mage-3",
    name: "Arcane Missile",
    manaCost: 6,
    damage: 10,
    description: "Fires a magical missile that never misses",
    classRestriction: ["mage"],
    levelRequirement: 3,
  },
  {
    id: "mage-4",
    name: "Lightning Bolt",
    manaCost: 12,
    damage: 15,
    description: "Calls down a bolt of lightning on the enemy",
    classRestriction: ["mage"],
    levelRequirement: 4,
  },
  {
    id: "mage-5",
    name: "Mana Shield",
    manaCost: 15,
    effect: "Absorbs damage using mana instead of health",
    description: "Creates a shield that uses mana to absorb damage",
    classRestriction: ["mage"],
    levelRequirement: 5,
  },
  {
    id: "mage-6",
    name: "Teleport",
    manaCost: 20,
    effect: "Escape from combat",
    description: "Teleport away from danger",
    classRestriction: ["mage"],
    levelRequirement: 6,
  },
  {
    id: "mage-7",
    name: "Meteor Strike",
    manaCost: 30,
    damage: 25,
    effect: "Hits all enemies",
    description: "Call down a meteor to damage all enemies",
    classRestriction: ["mage"],
    levelRequirement: 8,
  },
  {
    id: "mage-8",
    name: "Time Warp",
    manaCost: 25,
    effect: "Take an extra turn",
    description: "Bend time to take an additional turn",
    classRestriction: ["mage"],
    levelRequirement: 10,
  },
  {
    id: "mage-9",
    name: "Arcane Explosion",
    manaCost: 18,
    damage: 15,
    effect: "Hits all enemies",
    description: "Release a burst of arcane energy",
    classRestriction: ["mage"],
    levelRequirement: 7,
  },
  {
    id: "mage-10",
    name: "Polymorph",
    manaCost: 22,
    effect: "Enemy cannot attack for 2 turns",
    description: "Transform the enemy into a harmless creature",
    classRestriction: ["mage"],
    levelRequirement: 9,
  },
  {
    id: "mage-11",
    name: "Chain Lightning",
    manaCost: 35,
    damage: 20,
    effect: "Hits multiple enemies",
    description: "Lightning that chains between enemies",
    classRestriction: ["mage"],
    levelRequirement: 5,
    price: 500,
  },
  {
    id: "mage-12",
    name: "Ice Storm",
    manaCost: 40,
    damage: 25,
    effect: "Area damage and slows enemies",
    description: "Creates a devastating storm of ice",
    classRestriction: ["mage"],
    levelRequirement: 6,
    price: 750,
  },
  {
    id: "mage-13",
    name: "Phoenix Flame",
    manaCost: 45,
    damage: 30,
    effect: "Damage over time",
    description: "Summons the eternal flame of the phoenix",
    classRestriction: ["mage"],
    levelRequirement: 7,
    price: 1000,
  },
  {
    id: "mage-14",
    name: "Soul Drain",
    manaCost: 25,
    damage: 15,
    effect: "Heals for 50% of damage dealt",
    description: "Drains life force from enemies",
    classRestriction: ["mage"],
    levelRequirement: 4,
    price: 400,
  },
  {
    id: "mage-15",
    name: "Time Stop",
    manaCost: 50,
    effect: "Freezes all enemies for 2 turns",
    description: "Temporarily stops time for enemies",
    classRestriction: ["mage"],
    levelRequirement: 8,
    price: 1500,
  },
  // New mage spells
  {
    id: "mage-16",
    name: "Frost Nova",
    manaCost: 20,
    damage: 15,
    effect: "Freezes all enemies for 1 turn",
    description: "Release a burst of frost that freezes enemies",
    classRestriction: ["mage"],
    levelRequirement: 3,
    price: 400,
  },
  {
    id: "mage-17",
    name: "Arcane Barrier",
    manaCost: 25,
    effect: "Increases dodge chance by 20% for 3 turns",
    description: "Create a magical barrier that helps you evade attacks",
    classRestriction: ["mage"],
    levelRequirement: 4,
    price: 500,
  },
  {
    id: "mage-18",
    name: "Healing Wave",
    manaCost: 30,
    effect: "Heals for 40 health",
    description: "A wave of healing energy that restores health",
    classRestriction: ["mage"],
    levelRequirement: 5,
    price: 600,
  },
  {
    id: "mage-19",
    name: "Time Stop",
    manaCost: 25,
    damage: 5,
    effect: "Stuns enemy for 2 turns",
    description: "Temporarily freezes an enemy in time",
    classRestriction: ["mage"],
    levelRequirement: 4,
    price: 450,
  },
]

// Tank Spells
export const tankSpells: Spell[] = [
  {
    id: "tank-1",
    name: "Taunt",
    manaCost: 5,
    effect: "Enemy focuses attacks on you",
    description: "Taunt the enemy into attacking you",
    classRestriction: ["tank"],
    levelRequirement: 1,
  },
  {
    id: "tank-2",
    name: "Defensive Stance",
    manaCost: 8,
    effect: "Increases defense by 5 for 3 turns",
    description: "Take a defensive stance, increasing your defense",
    classRestriction: ["tank", "warrior"],
    levelRequirement: 3,
  },
  {
    id: "tank-3",
    name: "Provoke",
    manaCost: 10,
    damage: 5,
    effect: "Enemy focuses attacks on you",
    description: "Provoke the enemy, dealing damage and drawing attention",
    classRestriction: ["tank"],
    levelRequirement: 5,
  },
  {
    id: "tank-4",
    name: "Unbreakable",
    manaCost: 15,
    effect: "Reduces all damage by 50% for 2 turns",
    description: "Become nearly invulnerable for a short time",
    classRestriction: ["tank"],
    levelRequirement: 8,
  },
  // Tank shop spells
  {
    id: "tank-5",
    name: "Shield Wall",
    manaCost: 12,
    effect: "Increases defense by 8 for 2 turns",
    description: "Create an impenetrable wall with your shield",
    classRestriction: ["tank"],
    levelRequirement: 2,
    price: 300,
  },
  {
    id: "tank-6",
    name: "Retribution",
    manaCost: 15,
    effect: "Reflects 50% of damage back to attacker for 3 turns",
    description: "Reflect damage back to those who attack you",
    classRestriction: ["tank"],
    levelRequirement: 3,
    price: 400,
  },
  {
    id: "tank-7",
    name: "Guardian's Resolve",
    manaCost: 20,
    effect: "Heals 5 health per turn for 3 turns",
    description: "Channel your inner strength to regenerate health",
    classRestriction: ["tank"],
    levelRequirement: 4,
    price: 500,
  },
  // New tank spells
  {
    id: "tank-8",
    name: "Bulwark",
    manaCost: 25,
    effect: "Increases defense by 10 and dodge chance by 10% for 3 turns",
    description: "Raise your shield to block and deflect incoming attacks",
    classRestriction: ["tank"],
    levelRequirement: 5,
    price: 600,
  },
  {
    id: "tank-9",
    name: "Shield Slam",
    manaCost: 18,
    damage: 15,
    effect: "Stuns enemy for 2 turns",
    description: "Slam your shield into the enemy with tremendous force",
    classRestriction: ["tank"],
    levelRequirement: 6,
    price: 550,
  },
  {
    id: "tank-10",
    name: "Rallying Cry",
    manaCost: 30,
    effect: "Heals for 30 health and increases defense by 5 for 3 turns",
    description: "A powerful shout that bolsters your resolve",
    classRestriction: ["tank"],
    levelRequirement: 7,
    price: 700,
  },
  {
    id: "tank-11",
    name: "Concussive Blow",
    manaCost: 15,
    damage: 8,
    effect: "Stuns enemy for 1 turn",
    description: "A powerful blow that stuns the enemy",
    classRestriction: ["tank"],
    levelRequirement: 3,
    price: 350,
  },
]

// Get all spells
export const getAllSpells = (): Spell[] => {
  return [...warriorSpells, ...mageSpells, ...tankSpells]
}

// Get spells for a specific class
export const getSpellsForClass = (characterClass: CharacterClass): Spell[] => {
  return getAllSpells().filter((spell) => !spell.classRestriction || spell.classRestriction.includes(characterClass))
}

// Get spells available at a specific level
export const getSpellsForLevel = (characterClass: CharacterClass, level: number): Spell[] => {
  return getSpellsForClass(characterClass).filter((spell) => spell.levelRequirement && spell.levelRequirement <= level)
}

